project:
  type: "website"

website:
  title: "International Crime and Firearms Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd    


format:
  html:
    theme: cosmo
#    css: styles.css
    toc: true

